config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'translate', to: 'home#translate'
  get 'about_us', to: 'about_us#show'
  get 'maintenance', to: 'maintenance#show'
  scope 'markets' do
    get 'ocean_areas', to: 'markets#ocean_areas', as: :ocean_areas
    get 'land_areas', to: 'markets#land_areas', as: :land_areas
    get 'aerospace', to: 'markets#aerospace', as: :aerospace
  end
  scope 'products', as: 'products' do
    get 'car_mobile_communication_antenna_point_6', to: 'products#car_mobile_communication_antenna_point_6', as: :car_mobile_communication_antenna_point_6
    get 'car_mobile_communication_antenna_point_9', to: 'products#car_mobile_communication_antenna_point_9', as: :car_mobile_communication_antenna_point_9
    get 'portable_transportable_satellite_station_manual', to: 'products#portable_transportable_satellite_station_manual', as: :portable_transportable_satellite_station_manual
    get 'portable_transportable_satellite_station_auto', to: 'products#portable_transportable_satellite_station_auto', as: :portable_transportable_satellite_station_auto
    get 'shipboard_antenna_c', to: 'products#shipboard_antenna_c', as: :shipboard_antenna_c
    get 'shipboard_antenna_ku', to: 'products#shipboard_antenna_ku', as: :shipboard_antenna_ku
    get 'through_static_antenna', to: 'products#through_static_antenna', as: :through_static_antenna
    get 'super_terminal_3_in_1', to: 'products#super_terminal_3_in_1', as: :super_terminal_3_in_1
    get 'air_communication_antenna_7_mm', to: 'products#air_communication_antenna_7_mm', as: :air_communication_antenna_7_mm
    get 'ground_station_antenna_4_point_5', to: 'products#ground_station_antenna_4_point_5', as: :ground_station_antenna_4_point_5
    get 'ground_station_antenna_6_point_2', to: 'products#ground_station_antenna_6_point_2', as: :ground_station_antenna_6_point_2
  end
  resources :downloads do
    collection do
      get :video
    end
  end
  resources :jobs do
    collection do
      get :apply_form
      post :apply
    end
  end
  resources :vehicles do
    resources :angles
    member do
      get :reset
    end
  end
  resources :equipment do
    member do
      put :use
    end
  end
  namespace :cms do
    root 'dashboard#index'
    get 'dashboard', to: 'dashboard#index', as: :dashboard
    resources :vehicles do
      resources :angles
    end
    resources :angles do
      resources :categories
      resources :pictures
    end
    resources :categories do
      resources :equipment
    end
    resources :pictures
    resources :equipment
    resources :administrators
    resource :profile do
      get 'edit_password'
      put 'update_password'
    end
    get 'signin', to: 'sessions#new', as: :signin
    post 'signin', to: 'sessions#create'
    get 'signout', to: 'sessions#destroy', as: :signout
  end
end

app/models/administrator.rb
# -*- encoding : utf-8 -*-
class Administrator < ActiveRecord::Base
  attr_accessor :password, :password_confirmation
  has_many :notifications
  before_create :hash_password
  validates :account, presence: true, length: { maximum: 32 }
  validates :password, presence: true, length: { maximum: 16 }, on: :create
  validates :name, presence: true, length: { maximum: 50 }

  def authenticate password
    self.hashed_password == Digest::MD5.hexdigest(password) ? self : nil
  end

  def update_password password
    self.update(hashed_password: Digest::MD5.hexdigest(password))
  end

  protected
    def hash_password
      self.hashed_password = Digest::MD5.hexdigest self.password
    end
end

app/controllers/cms/administrators_controller.rb
# -*- encoding : utf-8 -*-
class Cms::AdministratorsController < Cms::BaseController
  
  def index
    @administrators = Administrator.page(page: params[:page])
  end
  
  def show
    @administrator = Administrator.find(params[:id])
  end
  
  def new
    @administrator = Administrator.new
  end
  
  def edit
    @administrator = Administrator.find(params[:id])
  end
  
  def create
    @administrator = Administrator.new(administrator_params)
    if @administrator.save
      redirect_to [:cms, @administrator], notice: '创建成功！'
    else
      render action: 'new'
    end
  end
  
  def update
    @administrator = Administrator.find(params[:id])
    if @administrator.update_attributes(administrator_params)
      redirect_to [:cms, @administrator], notice: '更新成功！'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @administrator = Administrator.find(params[:id])
    @administrator.destroy
    redirect_to admin_administrators_path
  end

  protected
  def administrator_params
    params.require(:administrator).permit!
  end
end

app/controllers/cms/angles_controller.rb
# -*- encoding : utf-8 -*-
class Cms::AnglesController < Cms::BaseController
  before_action :find_vehicle, only: [:new, :create]
  
  def index
    @angles = Angle.page(params[:page])
  end
  
  def show
    @angle = Angle.find(params[:id])
  end
  
  def new
    @angle = Angle.new
  end
  
  def edit
    @angle = Angle.find(params[:id])
  end
  
  def create
    @angle = @vehicle.angles.new(angle_params)
    if @angle.save
      redirect_to [:cms, @angle], notice: '创建成功！'
    else
      render action: 'new'
    end
  end
  
  def update
    @angle = Angle.find(params[:id])
    if @angle.update_attributes(angle_params)
      redirect_to [:cms, @angle], notice: '更新成功！'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @angle = Angle.find(params[:id])
    @angle.destroy
    redirect_to [:cms, @angle.vehicle]
  end

  protected
  def angle_params
    params.require(:angle).permit!
  end

  def find_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id])
  end
end

app/controllers/cms/base_controller.rb
# -*- encoding : utf-8 -*-
class Cms::BaseController < ApplicationController
  layout 'cms'

  before_action :authenticate
  
  def authenticate
    redirect_to cms_signin_path if session['administrator'].blank?
  end
end

app/controllers/cms/categories_controller.rb
# -*- encoding : utf-8 -*-
class Cms::CategoriesController < Cms::BaseController
  before_action :find_angle, only: [:new, :create]

  def index
    @categories = Category.page(params[:page])
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def new
    @category = Category.new
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def create
    @category = @angle.categories.new(category_params)
    if @category.save
      redirect_to [:cms, @angle], notice: '创建成功！'
    else
      render action: 'new'
    end
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to [:cms, @category.angle], notice: '更新成功！'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to [:cms, @category.angle]
  end

  protected
  def category_params
    params.require(:category).permit!
  end

  def find_angle
    @angle = Angle.find(params[:angle_id])
  end
end

app/controllers/cms/dashboard_controller.rb
# -*- encoding : utf-8 -*-
class Cms::DashboardController < Cms::BaseController
  
  def index
    
  end
end

app/controllers/cms/equipment_controller.rb
# -*- encoding : utf-8 -*-
class Cms::EquipmentController < Cms::BaseController
  before_action :find_category, only: [:new, :create]
  
  def index
    @equipment_list = Equipment.page(params[:page])
  end
  
  def show
    @equipment = Equipment.find(params[:id])
  end
  
  def new
    @equipment = Equipment.new
  end
  
  def edit
    @equipment = Equipment.find(params[:id])
  end
  
  def create
    @equipment = @category.equipment.new(equipment_params)
    if @equipment.save
      redirect_to [:cms, @equipment], notice: '创建成功！'
    else
      render action: 'new'
    end
  end
  
  def update
    @equipment = Equipment.find(params[:id])
    if @equipment.update_attributes(equipment_params)
      redirect_to [:cms, @equipment], notice: '更新成功！'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy
    redirect_to admin_equipments_path
  end

  protected
  def equipment_params
    params.require(:equipment).permit!
  end

  def find_category
    @category = Category.find(params[:category_id])
  end
end

app/controllers/cms/pictures_controller.rb
# -*- encoding : utf-8 -*-
class Cms::PicturesController < Cms::BaseController
  before_action :find_angle, only: [:new, :create]
  
  def index
    @pictures = Picture.page(params[:page])
  end
  
  def show
    @picture = Picture.find(params[:id])
  end
  
  def new
    @picture = Picture.new
  end
  
  def edit
    @picture = Picture.find(params[:id])
  end
  
  def create
    @picture = @angle.pictures.new(picture_params)
    @picture.code = equipment_params
    if @picture.save
      redirect_to [:cms, @angle], notice: '创建成功！'
    else
      render action: 'new'
    end
  end
  
  def update
    @picture = Picture.find(params[:id])
    @picture.code = equipment_params
    if @picture.update(picture_params)
      redirect_to [:cms, @picture.angle], notice: '更新成功！'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to @picture.vehicle
  end

  protected
  def picture_params
    begin
      params.require(:picture).permit!
    rescue ActionController::ParameterMissing
      {}
    end
  end

  def equipment_params
    params.require(:equipment).permit!
  end

  def find_angle
    @angle = Angle.find(params[:angle_id])
  end
end

app/controllers/cms/profiles_controller.rb
# -*- encoding : utf-8 -*-
class Cms::ProfilesController < Cms::BaseController
  
  def edit
    @administrator = Administrator.find(session['administrator']['id'])
  end
  
  def update
    @administrator = Administrator.find(session['administrator']['id'])
    if @administrator.update(profile_params)
      session['administrator']['name'] = @administrator.name
      redirect_to edit_cms_profile_path, notice: '更新成功！'
    else
      render action: 'edit'
    end
  end
  
  def update_password
    administrator = Administrator.find(session['administrator']['id'])
    if not administrator.authenticate(params[:orginal_password])
      redirect_to edit_password_cms_profile_path, alert: '修改失败！原密码不正确！'
    elsif not /^[A-Za-z0-9]{6,16}$/ =~ params[:new_password]
      redirect_to edit_password_cms_profile_path, alert: '修改失败！新密码应由6至16位的大小写字母及数字组成，请重试！'
    elsif not params[:new_password] == params[:password_confirmation]
      redirect_to edit_password_cms_profile_path, alert: '修改失败！两次新密码输入不一致！'
    else
      administrator.update_password params[:new_password]
      redirect_to edit_password_cms_profile_path, notice: '修改成功！'
    end
  end

  protected
  def profile_params
    params.require(:administrator).permit(:name)
  end
end

app/controllers/cms/sessions_controller.rb
# -*- encoding : utf-8 -*-
class Cms::SessionsController < Cms::BaseController
  skip_before_filter :authenticate, :find_notifications
  layout null: true

  def create
    administrator = Administrator.where(account: params[:account]).first.try(:authenticate, params[:password])
    unless administrator.blank?
      if administrator.available?
        administrator.update_attribute :last_signined_at, administrator.current_signined_at
        administrator.update_attribute :current_signined_at, Time.now
        session[:administrator] = { id: administrator.id, name: administrator.name, last_signined_at: administrator.last_signined_at }
        redirect_to cms_dashboard_path
      else
        redirect_to cms_signin_path, alert: '账号被禁用，无法登录'
      end
    else
      redirect_to cms_signin_path, alert: '账号或密码错误，请检查后重试'
    end
  end

  def destroy
    session[:administrator] = nil
    redirect_to cms_signin_path
  end
end

app/controllers/cms/vehicles_controller.rb
# -*- encoding : utf-8 -*-
class Cms::VehiclesController < Cms::BaseController
  
  def index
    @vehicles = Vehicle.page(params[:page])
  end
  
  def show
    @vehicle = Vehicle.find(params[:id])
  end
  
  def new
    @vehicle = Vehicle.new
  end
  
  def edit
    @vehicle = Vehicle.find(params[:id])
  end
  
  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      redirect_to [:cms, @vehicle], notice: '创建成功！'
    else
      render action: 'new'
    end
  end
  
  def update
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.update_attributes(vehicle_params)
      redirect_to [:cms, @vehicle], notice: '更新成功！'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
    redirect_to admin_vehicles_path
  end

  protected
  def vehicle_params
    params.require(:vehicle).permit!
  end
end

app/helpers/cms/base_helper.rb
# -*- encoding : utf-8 -*-
module Cms::BaseHelper

  def brac_t attribute
    t "activerecord.attributes.#{attribute}"
  end

  def brac_image image, options = {}
    css_class = (['img-responsive'] << (options[:class] || 'img-thumbnail')).flatten.join(' ')
    if options[:thumb]
      if image.url
        image_tag(image, style: "width: 120px;", class: css_class)
      else
        'N/A'
      end
    else
      if image.url
        image_tag(image, class: css_class)
      else
        text_field_tag(nil, '无', readonly: true, class: 'form-control')
      end
    end
  end

  def brac_date date
    date.try(:strftime, '%Y-%m-%d') || 'N/A'
  end

  def brac_time date
    date.try(:strftime, '%H:%M') || 'N/A'
  end

  def brac_datetime datetime
    datetime.try(:strftime, '%Y-%m-%d %H:%M') || 'N/A'
  end

  def brac_styled_boolean value
    raw(value ? '<span class="label label-success">是</span>' : '<span class="label label-danger">否</span>')
  end

  def brac_flash
    dismiss_btn = '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>'
    if flash[:alert]
      raw "<div class=\"alert alert-danger\">#{dismiss_btn}#{flash[:alert]}</div>"
    elsif flash[:notice]
      raw "<div class=\"alert alert-success\">#{dismiss_btn}#{flash[:notice]}</div>"
    end
  end

  def brac_paginate model
    paginate model
  end

  def styled_boolean_tag value, options = {}
    if options[:true_value].blank? or options[:false_value].blank?
      raw value ? "<span class=\"badge badge-success\">Y</span>" : "<span class=\"badge badge-important\">N</span>"
    else
      raw value ? "<span class=\"badge badge-success\">#{options[:true_value]}</span>" : "<span class=\"badge badge-important\">#{options[:false_value]}</span>"
    end
  end

  def hour_options
    options_for_select (6..18).map{|hour| ["#{hour.to_s.rjust(2, '0')}时", hour]}
  end

  def minute_options
    options_for_select (0..59).map{|minute| ["#{minute.to_s.rjust(2, '0')}分", minute]}
  end
end

app/views/cms/administrators/edit.html.erb
<div class="pageheader">
  <h2><i class="fa fa-pencil-square-o"></i> 系统管理 <span>编辑管理员</span></h2>
</div>
<div class="contentpanel">
  <%= render "admin/commons/error_messages", target: @administrator %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">管理员信息</h4>
    </div>
    <div class="panel-body panel-body-nopadding">
      <%= form_for [:admin, @administrator], html: { class: 'form-horizontal form-bordered' } do |f| %>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.account' %></label>
          <div class="col-sm-6">
            <%= f.text_field :account, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.name' %></label>
          <div class="col-sm-6">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'setting' %></label>
          <div class="col-sm-6">
            <div class="ckbox ckbox-default mt5">
              <%= f.check_box :available %>
              <label for="administrator_available"><%= brac_t 'administrator.available' %></label>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-12 text-center">
            <%= f.submit '提交', class: 'btn btn-primary' %>&nbsp;
            <input type="reset" value="重置" class="btn" />
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cms/administrators/index.html.erb
<div class="pageheader">
  <h2><i class="fa fa-list"></i> 系统管理 <span>管理员列表</span></h2>
</div>
<div class="contentpanel">
  <%= brac_flash %>
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive">
        <table class="table table-striped mb30">
          <thead>
            <tr>
              <th><%= brac_t 'administrator.account' %></th>
              <th><%= brac_t 'administrator.name' %></th>
              <th><%= brac_t 'administrator.available' %></th>
              <th></th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="5"><%= brac_paginate @administrators %></td>
            </tr>
          </tfoot>
          <tbody>
            <% @administrators.each do |administrator| %>
            <tr>
              <td><%= administrator.account %></td>
              <td><%= administrator.name %></td>
              <td><%= brac_styled_boolean administrator.available? %></td>
              <td class="table-action">
                <%= link_to raw('<i class="fa fa-file-text-o"></i>'), [:admin, administrator] %>
                <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_cms_administrator_path(administrator) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/cms/administrators/new.html.erb
<div class="pageheader">
  <h2><i class="fa fa-pencil-square-o"></i> 系统管理 <span>创建管理员</span></h2>
</div>
<div class="contentpanel">
  <%= render "admin/commons/error_messages", target: @administrator %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">管理员信息</h4>
    </div>
    <div class="panel-body panel-body-nopadding">
      <%= form_for [:admin, @administrator], html: { class: 'form-horizontal form-bordered' } do |f| %>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.account' %></label>
          <div class="col-sm-6">
            <%= f.text_field :account, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.name' %></label>
          <div class="col-sm-6">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.password' %></label>
          <div class="col-sm-6">
            <%= f.text_field :password, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.password_confirmation' %></label>
          <div class="col-sm-6">
            <%= f.text_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'setting' %></label>
          <div class="col-sm-6">
            <div class="ckbox ckbox-default mt5">
              <%= f.check_box :available %>
              <label for="administrator_available"><%= brac_t 'administrator.available' %></label>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-12 text-center">
            <%= f.submit '提交', class: 'btn btn-primary' %>&nbsp;
            <input type="reset" value="重置" class="btn" />
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cms/administrators/show.html.erb
<div class="pageheader">
  <h2><i class="fa fa-file-text-o"></i> 系统管理 <span>查看管理员</span></h2>
</div>
<div class="contentpanel">
  <%= brac_flash %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">管理员信息</h4>
    </div>
    <div class="panel-body panel-body-nopadding">
      <%= form_tag nil, class: 'form-horizontal form-bordered' do %>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.account' %></label>
          <div class="col-sm-6">
            <%= text_field_tag nil, @administrator.account, readonly: true, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.name' %></label>
          <div class="col-sm-6">
            <%= text_field_tag nil, @administrator.name, readonly: true, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.available' %></label>
          <div class="col-sm-6">
            <div class="mt5"><%= brac_styled_boolean @administrator.available? %></div>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"><%= brac_t 'administrator.last_signined_at' %></label>
          <div class="col-sm-6">
            <%= text_field_tag nil, brac_datetime(@administrator.last_signined_at), readonly: true, class: 'form-control' %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="panel-footer">
      <%= link_to '返回管理员列表', cms_administrators_path, class: 'btn btn-default' %>&nbsp;
      <%= link_to '编辑', edit_cms_administrator_path(@administrator), class: 'btn btn-default' %>&nbsp;
    </div>
  </div>
</div>