config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'translate', to: 'home#translate'
  get 'about_us', to: 'about_us#show'
  get 'maintenance', to: 'maintenance#show'
  scope 'markets' do
    get 'ocean_areas', to: 'markets#ocean_areas', as: :ocean_areas
    get 'land_areas', to: 'markets#land_areas', as: :land_areas
    get 'aerospace', to: 'markets#aerospace', as: :aerospace
  end
  scope 'products', as: 'products' do
    get 'car_mobile_communication_antenna_point_6', to: 'products#car_mobile_communication_antenna_point_6', as: :car_mobile_communication_antenna_point_6
    get 'car_mobile_communication_antenna_point_9', to: 'products#car_mobile_communication_antenna_point_9', as: :car_mobile_communication_antenna_point_9
    get 'portable_transportable_satellite_station_manual', to: 'products#portable_transportable_satellite_station_manual', as: :portable_transportable_satellite_station_manual
    get 'portable_transportable_satellite_station_auto', to: 'products#portable_transportable_satellite_station_auto', as: :portable_transportable_satellite_station_auto
    get 'shipboard_antenna_c', to: 'products#shipboard_antenna_c', as: :shipboard_antenna_c
    get 'shipboard_antenna_ku', to: 'products#shipboard_antenna_ku', as: :shipboard_antenna_ku
    get 'through_static_antenna', to: 'products#through_static_antenna', as: :through_static_antenna
    get 'super_terminal_3_in_1', to: 'products#super_terminal_3_in_1', as: :super_terminal_3_in_1
    get 'air_communication_antenna_7_mm', to: 'products#air_communication_antenna_7_mm', as: :air_communication_antenna_7_mm
    get 'ground_station_antenna_4_point_5', to: 'products#ground_station_antenna_4_point_5', as: :ground_station_antenna_4_point_5
    get 'ground_station_antenna_6_point_2', to: 'products#ground_station_antenna_6_point_2', as: :ground_station_antenna_6_point_2
  end
  resources :downloads do
    collection do
      get :video
    end
  end
  resources :jobs do
    collection do
      get :apply_form
      post :apply
    end
  end
  resources :vehicles do
    resources :angles
    member do
      get :reset
    end
  end
  resources :equipment do
    member do
      put :use
    end
  end
  namespace :cms do
    root 'dashboard#index'
    get 'dashboard', to: 'dashboard#index', as: :dashboard
    resources :vehicles do
      resources :angles
    end
    resources :angles do
      resources :categories
      resources :pictures
    end
    resources :categories do
      resources :equipment
    end
    resources :pictures
    resources :equipment
    resources :administrators
    resource :profile do
      get 'edit_password'
      put 'update_password'
    end
    get 'signin', to: 'sessions#new', as: :signin
    post 'signin', to: 'sessions#create'
    get 'signout', to: 'sessions#destroy', as: :signout
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :angles
end

app/controllers/cms/vehicles_controller.rb
# -*- encoding : utf-8 -*-
class Cms::VehiclesController < Cms::BaseController
  
  def index
    @vehicles = Vehicle.page(params[:page])
  end
  
  def show
    @vehicle = Vehicle.find(params[:id])
  end
  
  def new
    @vehicle = Vehicle.new
  end
  
  def edit
    @vehicle = Vehicle.find(params[:id])
  end
  
  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      redirect_to [:cms, @vehicle], notice: '创建成功！'
    else
      render action: 'new'
    end
  end
  
  def update
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.update_attributes(vehicle_params)
      redirect_to [:cms, @vehicle], notice: '更新成功！'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
    redirect_to admin_vehicles_path
  end

  protected
  def vehicle_params
    params.require(:vehicle).permit!
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < BaseController
  def show
    @vehicle = Vehicle.find(params[:id])
    @angle = begin
      @vehicle.angles.find(params[:angle_id])
    rescue ActiveRecord::RecordNotFound
      @vehicle.angles.first
    end
    session["vehicle_#{@vehicle.id}_angle_#{@angle.id}"] ||= Hash[@angle.categories.map{|category| [category.id.to_s, '0']}]
    @picture = @angle.pictures.find_by_equipment(session["vehicle_#{@vehicle.id}_angle_#{@angle.id}"])
  end

  def reset
    @vehicle = Vehicle.find(params[:id])
    @angle = @vehicle.angles.find(params[:angle_id])
    session["vehicle_#{@vehicle.id}_angle_#{@angle.id}"] = Hash[@angle.categories.map{|category| [category.id.to_s, '0']}]
    redirect_to vehicle_path(@vehicle, angle_id: @angle.id)
  end
end

app/views/vehicles/show.html.erb
<div role="main" class="main">
  <section class="page-top">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="breadcrumb">
            <li><%= link_to '首页', root_path %></li>
            <li class="active">在线组装</li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h1><%= @vehicle.name %></h1>
        </div>
      </div>
    </div>
  </section>
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="blog-posts single-post">
          <article class="post post-large blog-single-post">
            <div class="post-image">
              <div>
                <div class="img-thumbnail">
                  <%= image_tag @picture.try(:file), class: 'img-responsive' %>
                </div>
              </div>
            </div>
          </article>
        </div>
      </div>
      <div class="col-md-3">
        <aside class="sidebar">
          <h4>视角</h4>
          <ul class="nav nav-list primary push-bottom">
            <% @vehicle.angles.each do |angle| %>
            <li<%= raw(' class="active"') if angle.id == @angle.id %>><%= link_to angle.name, vehicle_path(@vehicle, angle_id: angle.id) %></li>
            <% end %>
          </ul>
          <% @angle.categories.each do |category| %>
          <h5><%= category.name %></h5>
          <ul class="nav nav-list primary push-bottom">
            <% category.equipment.each do |equipment| %>
            <li><%= link_to equipment.name, equipment, 'data-toggle' => 'modal', 'data-target' => '.show-equipment-modal' %></li>
            <% end %>
          </ul>
          <% end %>
          <%= link_to '重置设备', reset_vehicle_path(@vehicle, angle_id: @angle.id), class: 'btn btn-primary' %>
        </aside>
        <!-- <div id="accordion">
          <h3>Section 1</h3>
          <div>
            <p>
            Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer
            ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit
            amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut
            odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.
            </p>
          </div>
          <h3>Section 2</h3>
          <div>
            <p>
            Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet
            purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor
            velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In
            suscipit faucibus urna.
            </p>
          </div>
          <h3>Section 3</h3>
          <div>
            <p>
            Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.
            Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero
            ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis
            lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.
            </p>
            <ul>
              <li>List item one</li>
              <li>List item two</li>
              <li>List item three</li>
            </ul>
          </div>
          <h3>Section 4</h3>
          <div>
            <p>
            Cras dictum. Pellentesque habitant morbi tristique senectus et netus
            et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
            faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
            mauris vel est.
            </p>
            <p>
            Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
            inceptos himenaeos.
            </p>
          </div>
        </div> -->
      </div>
    </div>
  </div>
</div>
<div id="showEquipmentModal" class="modal fade show-equipment-modal" tabindex="-1" role="dialog" aria-labelledby="showEquipment" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>
<% content_for :javascript do %>
  <script>
  $('body').on('hidden.bs.modal', '.modal', function () {
    $(this).removeData('bs.modal');
  });
  </script>
<% end %>